from django.contrib.gis.geos import GEOSGeometry, MultiPoint, MultiPolygon, MultiLineString
from . import models

layers = {
        'neighborhood_development_18_001': { 
            'app_label': 'neighborhood_development_18',
            'name': 'Bike Parking',
            'type': 'Slide',
            'endpoint':'',
            'visualization': 'ScatterPlotMap',
            'multi_geom_class': MultiPoint, 
            'model_name': models.BikeParking,
            'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
            'primary_attribute_label': None,
            'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
            'secondary_attribute_label': None,
            'date_attribute_column': None, 
            'date_granularity': None,
            'default_date_filter': '2017',
            'min_date': None,
            'max_date': None,
        },
        'neighborhood_development_18_002': {
          'app_label': 'neighborhood_development_18',
          'name': 'Bike Lanes',
          'type': 'Slide',
          'endpoint':'',
          'visualization': 'PathMap',
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'multi_geom_class': MultiLineString, 
          'model_name': models.BikeLane,
          'date_attribute_column': None, 
          'date_granularity': None,
          'default_date_filter': '2018',
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_003': {
          'name': 'Parks',
          'type': 'Slide',
          'endpoint':'',
          'visualization': 'PolygonPlotMap', 
          'multi_geom_class': MultiPolygon, 
          'model_name': models.Park,
          'primary_attribute_column': 'name', # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': 'Park',
          'secondary_attribute_column': 'acres', # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': 'Park Acreage',
          'date_attribute_column': None, 
          'date_granularity': None,
          'default_date_filter': '2018',
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_004': {
          'name': 'Multi-use Trails',
          'type': 'Slide',
          'endpoint':'',
          'visualization': 'PathMap',
          'multi_geom_class': MultiLineString, 
          'model_name': models.MultiuseTrail,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None, 
          'date_granularity': None,
          'default_date_filter': '2018',
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_005': {
          'name': 'Community Gardens',
          'type': 'Slide',
          'endpoint':'',
          'visualization': 'SmallPolygonMap',
          'multi_geom_class': MultiPolygon, 
          'model_name': models.CommunityGarden,
          'primary_attribute_column': 'sitename', # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': 'Name',
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None, 
          'date_granularity': None,
          'default_date_filter': '2017',
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_006': {
          'name': 'Bike Greenways',
          'type': 'Slide',
          'endpoint':'',
          'visualization': 'PathMap',
          'multi_geom_class': MultiLineString, 
          'model_name': models.BikeGreenway,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None, 
          'date_granularity': None,
          'default_date_filter': '2018',
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_007': {
          'name': 'Rail Stops',
          'type': 'Slide',
          'endpoint':'',
          'visualization': 'ScatterPlotMap',
          'multi_geom_class': MultiPoint, 
          'model_name': models.RailStop,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None, 
          'date_granularity': None,
          'default_date_filter': '2016',
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_008': {
          'name': 'Grocery Stores',
          'type': 'Slide',
          'endpoint':'',
          'visualization': 'ScatterPlotMap',
          'multi_geom_class': MultiPoint, 
          'model_name': models.RailStop,
          'primary_attribute_column': 'company_na', # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': 'Name',
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None, 
          'date_granularity': None,
          'default_date_filter': '2018',
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_009': {
          'name': 'Demolitions',
          'type': 'Slide',
          'endpoint':'',
          'visualization': 'ScatterPlotMap',
          'multi_geom_class': MultiPoint, 
          'model_name': models.Demolition,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': 'year', 
          'date_granularity': 'year',
          'default_date_filter': '2018',
          'min_date': '2000',
          'max_date': '2018',
        },
        'neighborhood_development_18_010': {
          'app_label': 'neighborhood_development_18',
          'name': 'Camp Sweeps',
          'type': 'Slide',
          'endpoint':'',
          'visualization': 'ScatterPlotMap',
          'multi_geom_class': MultiPoint, 
          'model_name': models.CampSweep,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': 'formatted_date',
          'date_granularity': 'month',
          'default_date_filter': 'Apr2018',
          'min_date': 'Oct2016',
          'max_date': 'May2018',
        },
        'neighborhood_development_18_011': {
          'app_label': 'neighborhood_development_18',
          'name': 'Camp Reports',
          'type': 'Slide',
          'endpoint':'',
          'visualization': 'ScatterPlotMap',
          'multi_geom_class': MultiPoint, 
          'model_name': models.CampReport,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': 'date',
          'date_granularity': 'year',
          'default_date_filter': '2018',
          'min_date': '2015',
          'max_date': '2018',
        },
        'neighborhood_development_18_012': {
          'app_label': 'neighborhood_development_18',
          'name': 'Bus Stops',
          'type': 'Slide',
          'endpoint':'',
          'visualization': 'ScatterPlotMap',
          'multi_geom_class': MultiPoint, 
          'model_name': models.BusStop,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': '2018',
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_013': {
          'app_label': 'neighborhood_development_18',
          'name': 'Bike Estimates',
          'type': 'Slide',
          'endpoint':'',
          'visualization': 'ScatterPlotMap',
          'multi_geom_class': MultiPoint, 
          'model_name': models.BikeDailyEstimate,
          'primary_attribute_column': 'year_2016', # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': 'Daily Estimates of Bike Traffic',
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': '2016',
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_014': {
          'app_label': 'neighborhood_development_18',
          'name': 'Bike Counts',
          'type': 'Slide',
          'endpoint':'',
          'visualization': 'ScatterPlotMap',
          'multi_geom_class': MultiPolygon, 
          'model_name': models.BikeCount,
          'primary_attribute_column': 'year_2017', # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': 'Actual Bike Count',
          'secondary_attribute_column': 'count_time', # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': 'Count Time',
          'date_attribute_column': None, 
          'date_granularity': None,
          'default_date_filter': '2017',
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_015': {
          'app_label': 'neighborhood_development_18',
          'name': 'Voters 18 to 25',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          'model_name': models.Voter18to25,
          'primary_attribute_column': 'pct_18_25', # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': 'Registered Voters 18 to 25',
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': 'year', 
          'date_granularity': 'year',
          'default_date_filter': '2016',
          'min_date': '2006',
          'max_date': '2016',
        },
        'neighborhood_development_18_016': {
          'app_label': 'neighborhood_development_18',
          'name': 'Voters 26 to 32',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          'model_name': models.Voter26to32,
          'primary_attribute_column': 'pct_26_32', # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': 'Registered Voters 26 to 32',
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': 'year', 
          'date_granularity': 'year',
          'default_date_filter': '2016',
          'min_date': '2006',
          'max_date': '2016',
        },
        'neighborhood_development_18_017': {
          'app_label': 'neighborhood_development_18',
          'name': 'Voters 33 to 39',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          'model_name': models.Voter33to39,
          'primary_attribute_column': 'pct_33_39', # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': 'Registered Voters 33 to 39',
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': 'year', 
          'date_granularity': 'year',
          'default_date_filter': '2016',
          'min_date': '2006',
          'max_date': '2016',
        },
        'neighborhood_development_18_018': {
          'app_label': 'neighborhood_development_18',
          'name': 'Voters 40 to 49',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          'model_name': models.Voter40to49,
          'primary_attribute_column': 'pct_40_49', # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': 'Registered Voters 40 to 49',
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': 'year', 
          'date_granularity': 'year',
          'default_date_filter': '2016',
          'min_date': '2006',
          'max_date': '2016',
        },
        'neighborhood_development_18_019': {
          'app_label': 'neighborhood_development_18',
          'name': 'Voters 50 Plus',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          'model_name': models.Voter50Plus,
          'primary_attribute_column': 'pct_50_plus', # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': 'Registered Voters 50 plus',
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': 'year', 
          'date_granularity': 'year',
          'default_date_filter': '2016',
          'min_date': '2006',
          'max_date': '2016',
        },
        'neighborhood_development_18_020': {
          'app_label': 'neighborhood_development_18',
          'name': 'Monthly Campsite Reports',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          'model_name': models.ReportsByMonth,
          'primary_attribute_column': 'count', # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': 'Count',
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': 'formatted_date',
          'date_granularity': 'month',
          'default_date_filter': 'Apr2018', 
          'min_date': 'Dec2015',
          'max_date': 'Apr2018',
        },
        'neighborhood_development_18_021': { ##TODO 
          'app_label': 'neighborhood_development_18',
          'name': 'Total Population',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          # 'model_name': models.Model,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': None, 
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_022': { ##TODO 
          'app_label': 'neighborhood_development_18',
          'name': 'Median Houshold Income',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          # 'model_name': models.Model,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': None, 
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_023': { ##TODO 
          'app_label': 'neighborhood_development_18',
          'name': 'Median Gross Rent',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          # 'model_name': models.Model,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': None, 
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_024': { ##TODO 
          'app_label': 'neighborhood_development_18',
          'name': 'Evictions',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          # 'model_name': models.Model,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': None, 
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_025': { ##TODO 
          'app_label': 'neighborhood_development_18',
          'name': 'Renter Occupied Households',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          # 'model_name': models.Model,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': None, 
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_026': { ##TODO 
          'app_label': 'neighborhood_development_18',
          'name': 'Rent Burden',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          # 'model_name': models.Model,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': None, 
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_027': { ##TODO 
          'app_label': 'neighborhood_development_18',
          'name': 'Households with Children',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          # 'model_name': models.Model,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': None, 
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_028': { ##TODO 
          'app_label': 'neighborhood_development_18',
          'name': 'Housholders Living Alone',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          # 'model_name': models.Model,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': None, 
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_029': { ##TODO 
          'app_label': 'neighborhood_development_18',
          'name': 'Housholders Living Alone',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          # 'model_name': models.Model,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': None, 
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_030': { ##TODO 
          'app_label': 'neighborhood_development_18',
          'name': 'Owner Occupied Housholds',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          # 'model_name': models.Model,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': None, 
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_31': { ##TODO 
          'app_label': 'neighborhood_development_18',
          'name': 'Percent Renter Occupied',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          # 'model_name': models.Model,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': None, 
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_032': { ##TODO 
          'app_label': 'neighborhood_development_18',
          'name': 'Eviction Rate',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          # 'model_name': models.Model,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': None, 
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_033': { ##TODO 
          'app_label': 'neighborhood_development_18',
          'name': 'Poverty Rate',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          # 'model_name': models.Model,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': None, 
          'min_date': None,
          'max_date': None,
        },
        'neighborhood_development_18_034': { ##TODO 
          'app_label': 'neighborhood_development_18',
          'name': 'Households with Seniors',
          'type': 'Foundation',
          'endpoint':'',
          'visualization': 'ChoroplethMap',
          'multi_geom_class': MultiPolygon, 
          # 'model_name': models.Model,
          'primary_attribute_column': None, # When updating primary_attribute_column, update in model as well
          'primary_attribute_label': None,
          'secondary_attribute_column': None, # When updating secondary_attribute_column, update in model as well
          'secondary_attribute_label': None,
          'date_attribute_column': None,
          'date_granularity': None,
          'default_date_filter': None, 
          'min_date': None,
          'max_date': None,
        },
}
