from neighborhood_development_18.layers import layers as neighborhood_development_18_layers
from transportation_systems_18.layers import layers as transportation_systems_18_layers
from disaster_resilience_18.layers import layers as disaster_resilience_18_layers
from housing_affordability_18.layers import layers as housing_affordability_18_layers

layers = {}

layers.update(neighborhood_development_18_layers)
layers.update(transportation_systems_18_layers)
layers.update(disaster_resilience_18_layers)
layers.update(housing_affordability_18_layers)

