# Generated by Django 2.0.1 on 2018-08-11 21:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeParkingModel',
            fields=[
                ('objectid', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(db_column='geom', srid=4326)),
            ],
            options={
                'db_table': 'bike_parking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemolitionsModel',
            fields=[
                ('objectid', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(db_column='geom', srid=4326)),
                ('description', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'demolitions',
                'managed': False,
            },
        ),
    ]
