# Generated by Django 2.0.1 on 2018-08-14 20:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_development_18', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeLanesModel',
            fields=[
                ('objectid', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(db_column='geom', srid=4326)),
            ],
            options={
                'db_table': 'bike_lanes',
                'managed': False,
            },
        ),
    ]
