# Generated by Django 2.0.1 on 2018-08-14 22:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_development_18', '0003_monthlycampreportsmoel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCampReportsModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(db_column='geom', srid=4326)),
            ],
            options={
                'db_table': 'campsite_reports_by_month_neigh',
                'managed': False,
            },
        ),
    ]
