# Generated by Django 2.0.1 on 2018-08-15 18:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_development_18', '0004_monthlycampreportsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeParking',
            fields=[
                ('objectid', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'bike_parking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demolition',
            fields=[
                ('objectid', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'demolitions',
                'managed': False,
            },
        ),
    ]
