# Generated by Django 2.0.1 on 2018-08-15 18:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_development_18', '0005_bikeparking_demolition'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeCount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('count_time', models.CharField(max_length=5)),
                ('year_2017', models.IntegerField(blank=True, db_column='2017', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'bike_counts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BikeDailyEstimate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year_2016', models.IntegerField(blank=True, db_column='2016', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'bike_daily_estimates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BikeGreenway',
            fields=[
                ('objectid', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'bike_greenways',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BikeLane',
            fields=[
                ('objectid', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'db_table': 'bike_lanes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlockGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=50)),
                ('median_household_income', models.IntegerField()),
                ('Median_gross_rent', models.IntegerField()),
                ('evictions', models.IntegerField()),
                ('eviction_rate', models.FloatField()),
                ('renter_occupied_households', models.IntegerField()),
                ('rent_burden', models.FloatField()),
                ('poverty_rate', models.FloatField()),
                ('pctrenter_occupied', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'evictions_blockgroups_scope',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('keyitem', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'bus_stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampReport',
            fields=[
                ('id', models.IntegerField(db_column='ItemID', primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'campsite_reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampSweep',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('formatted_date', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'camp_sweeps_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityGarden',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sitename', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'community_gardens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IMSNeighborhood',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=50)),
                ('total_population', models.IntegerField()),
                ('pc_household_with_children_under_18', models.FloatField()),
                ('pc_household_with_individuals_65_ovr', models.FloatField()),
                ('pc_owner_occupied_housing_units', models.FloatField()),
                ('pc_householders_living_alone', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'ims_neighborhood_demographics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MultiuseTrail',
            fields=[
                ('ogc_fid', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'db_table': 'active_multiuse_trail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NeighborhoodVoterRegistrationByAgeGroup',
            fields=[
                ('neighborhood', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('pct_18_25', models.FloatField()),
                ('pct_26_32', models.FloatField()),
                ('pct_33_39', models.FloatField()),
                ('pct_40_49', models.FloatField()),
                ('pct_50_plus', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'neighborhood_voters_ages_over_time_geom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('acres', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'parks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParksTrail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'parks_trails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RailStop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'rail_stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportsByMonth',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('formatted_date', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'campsite_reports_by_month_neigh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetailGrocer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_na', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'retail_grocers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_inventoried', models.DateTimeField(blank=True, null=True)),
                ('common', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'trees',
                'managed': False,
            },
        ),
    ]
