# Generated by Django 2.0.1 on 2018-08-30 02:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_development_18', '0006_bikecount_bikedailyestimate_bikegreenway_bikelane_blockgroup_busstop_campreport_campsweep_communityg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter18to25',
            fields=[
                ('neighborhood', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('pct_18_25', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'neighborhood_voters_ages_over_time_geom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voter26to32',
            fields=[
                ('neighborhood', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('pct_26_32', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'neighborhood_voters_ages_over_time_geom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voter33to39',
            fields=[
                ('neighborhood', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('pct_33_39', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'neighborhood_voters_ages_over_time_geom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voter40to49',
            fields=[
                ('neighborhood', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('pct_40_49', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'neighborhood_voters_ages_over_time_geom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voter50Plus',
            fields=[
                ('neighborhood', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('pct_50_plus', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'neighborhood_voters_ages_over_time_geom',
                'managed': False,
            },
        ),
    ]
