# Generated by Django 2.0.1 on 2018-08-26 20:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_resilience_18', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusResponse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(db_column='wkb_geometry', srid=4326)),
                ('census_response_rate', models.FloatField()),
            ],
            options={
                'db_table': 'disaster_neighborhood_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Landslide',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(db_column='wkb_geometry', srid=4326)),
                ('pgd_landslide_dry_mean_di', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'disaster_neighborhood_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Liquefaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(db_column='wkb_geometry', srid=4326)),
                ('pgd_total_wet_mean_di', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'disaster_neighborhood_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shaking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(db_column='wkb_geometry', srid=4326)),
                ('pgv_site_mean_mmi_txt', models.CharField(max_length=10)),
                ('pgv_site_mean_desc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'disaster_neighborhood_view',
                'managed': False,
            },
        ),
    ]
