# Generated by Django 2.0.1 on 2018-08-26 20:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_systems_18', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockChange',
            fields=[
                ('census_block', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stops_pct_change', models.FloatField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(db_column='hull_4326', null=True, srid=4326)),
            ],
            options={
                'db_table': 'census_block_change_hull',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('crash_id', models.IntegerField(primary_key=True, serialize=False)),
                ('crash_dt', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(db_column='geom_point', null=True, srid=4326)),
            ],
            options={
                'db_table': 'crash',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RouteChange',
            fields=[
                ('shape_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pct_change', models.FloatField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(db_column='geom_linestring', null=True, srid=4326)),
            ],
            options={
                'db_table': 'route_change',
                'managed': False,
            },
        ),
    ]
